name: gw3099
channels:
  - conda-forge
dependencies:

  # primary dependencies
  - python
  - numpy<2.0.0
  - matplotlib
  - pandas
  - scipy
  - flopy

  # other class dependencies
  - pip
  - git
  - jupyter
  - jupytext
  - jupyterlab
  - openpyxl
  - xlrd
  - netcdf4
  - pyshp
  - rasterio
  - rasterstats
  - fiona
  - descartes
  - pyproj
  - shapely
  - filelock
  - geos
  - geojson
  - geopandas
  - xarray
  - rioxarray
  - uxarray
  - xugrid
  - pyyaml
  - rtree
  - pyvista
  - vtk
  - imageio
  - requests
  - pytest
  - pytest-order
  - pytest-xdist
  - statsmodels
  - modflowapi
  - pymetis
  - pyemu
  - pestpp
  - hvplot
  - pywatershed [--only-deps]

  # pip dependencies
  - pip:
    - jupyter_black
    - git+https://github.com/jararias/mpsplines.git
    - git+https://github.com/paknorton/pyPRMS.git@development
    - "--editable git+https://github.com/EC-USGS/pywatershed.git@develop#egg=pywatershed"
