name: gw3099
channels:
  - conda-forge
dependencies:

  # primary dependencies
  - python
  - numpy
  - matplotlib
  - pandas
  - scipy
  - flopy>=3.8

  # other class dependencies
  - dataretrieval
  - pip
  - git
  - jupyter
  - jupytext
  - jupyterlab
  - openpyxl
  - xlrd
  - netcdf4
  - pyshp
  - rasterio
  - rasterstats
  - fiona
  - descartes
  - pyproj
  - shapely
  - geos
  - geojson
  - geopandas
  - xarray
  - rioxarray
  - uxarray
  - xugrid
  - pyyaml
  - rtree
  - pyvista
  - vtk
  - imageio
  - requests
  - pytest
  - statsmodels
  - modflowapi
  - pymetis
  - pyemu>=1.3.7
  - pestpp
  - pywatershed [--only-deps]

  # pip dependencies
  - pip:
    - git+https://github.com/EC-USGS/pywatershed.git@develop
   
